name: release

on:
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x

      - name: Build
        run: make build

      - name: Bump version
        uses: paulhatch/semantic-version@v5.3.0
        id: semantic
        with:
          # The prefix to use to identify tags
          tag_prefix: ""
          major_pattern: "DO-NOT-USE-MAJOR"
          minor_pattern: "DO-NOT-USE-MINOR"
          # Force to read branch name as version.
          # - hotfix/0.1   becomes 0.1.1
          # - hotfix/1.2   becomes 1.2.1
          # - hotfix/0.1.1 will be ignored!
          version_from_branch: "hotfix/([0-9]+.[0-9]+$|[0-9]+)$/"

      - name: Show bump results
        run: |
          echo "version:     ${{ steps.semantic.outputs.version }}"        # e.g. 0.2.0
          echo "version_tag: ${{ steps.semantic.outputs.version_tag }}"    # e.g. 0.2.0
          echo "increment:   ${{ steps.semantic.outputs.increment }}"      # e.g. 10
          echo "changed:     ${{ steps.semantic.outputs.changed }}"        # e.g. true / false
          echo "current-sha: ${{ steps.semantic.outputs.current_commit }}" # e.g. e909b0f5089bae7c8b7e22def69da02962b842fd

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.semantic.outputs.version_tag }}
          commit: ${{ github.ref }}
          artifacts: "_output/.bin/protoc-gen-openapi.*"
          allowUpdates: false
          generateReleaseNotes: true
          skipIfReleaseExists: true
